name: Deploy to Heroku

on: [push]

jobs:
  Heroku:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ğŸ”¥ï¸
        uses: actions/checkout@v2

      - name: Install Packages ğŸ§³
        run: |
          npm install

      - name: npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: build ğŸ—ï¸
        run: |
          npm --version
          npm run build

      - name: Deploy ğŸš€
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
