#name: Deploy to Heroku
#
#on: [push]
#
#jobs:
#  Heroku:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout ğŸ”¥ï¸
#        uses: actions/checkout@v2
#
#      - name: Node inst
#        uses: actions/setup-node@v2
#        with:
#          node-version: "16"
#
#      - name: npm vers ğŸ—ï¸
#        run: |
#          npm --version
#
#      - name: Install Packages ğŸ§³
#        run: |
#          npm install --legacy-peer-deps
#          npm install --legacy-peer-deps -ws
#
#      - name: Install Packages front ğŸ§³
#        run: |
#          npm install --legacy-peer-deps
#          working-directory: ./packages/frontend
#
#      - name: Install Packages back ğŸ§³
#        run: |
#          npm install --legacy-peer-deps
#          working-directory: ./packages/backend
#
#      - name: build ğŸ—ï¸
#        run: |
#          npm --version
#          npm run build
#
#      - name: build heroku ğŸ—ï¸
#        - uses: actions/setup-node@v2
#            with:
#              node-version: "16"
#        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#            with:
#              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#              heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
#              heroku_email: ${{secrets.HEROKU_EMAIL}}
#
#  #      - name: Deploy ğŸš€ |
#  #        run:|
#  #        -  uses: actions/setup-node@v2
#  #        -  uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
#  #           with:
#  #             node-version: '16'
#  #             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#  #             heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
#  #             heroku_email: ${{secrets.HEROKU_EMAIL}}
##  build:
##    runs-on: ubuntu-latest
##    steps:
##      - uses: actions/setup-node@v2
##        with:
##          node-version: "16"
##      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
##        with:
##          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
##          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
##          heroku_email: ${{secrets.HEROKU_EMAIL}}
