name: Build

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node inst
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: npm vers üèóÔ∏è
        run: |
          npm --version

      - name: Install Packages üß≥
        run: |
          npm install --legacy-peer-deps
          npm install --legacy-peer-deps -ws
      - name: Install Packages front üß≥
        working-directory: ./packages/frontend
        run: |
          npm install --legacy-peer-deps

      - name: Install Packages back üß≥
        working-directory: ./packages/backend
        run: |
          npm install --legacy-peer-deps

      - name: Lint check
        run: |
          npm run lint

      - name: Run  Jest  T-E-S-T
        run: |
          npm run test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0

      - name: webpack  build
        run: |
          npm run build

      - name: Deploy to Prod üöÄ
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Deploy to Stage üöÄ
        if: ${{ github.ref != 'refs/heads/dev' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_STAGE}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Set env
        if: ${{ !success() }}
        run: echo "APP_VERSION='–°–±–æ—Ä–∫–∞ –∑–∞–≤–µ—Ä—à–µ–Ω–∞ '${{ job.status }}' —Å–º–æ—Ç—Ä–∏ –ª–æ–≥–∏'" >> $GITHUB_ENV

      - name: Set env failure
        if: ${{ !failure() }}
        run: echo "APP_VERSION='–°–±–æ—Ä–∫–∞ –ù–ï –∑–∞–≤–µ—Ä—à–µ–Ω–∞ '${{ job.status }}' —Å–º–æ—Ç—Ä–∏ –ª–æ–≥–∏'" >> $GITHUB_ENV

      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "–ë–æ—Ç —Å–±–æ—Ä–æ—á–Ω–æ–≥–æ –∫–æ–Ω–≤–µ–µ—Ä–∞"
          SLACK_TITLE: "–°–±–æ—Ä–∫–∞ –∑–∞–≤–µ—Ä—à–µ–Ω–∞"
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: ${{ env.STEPVAR }}
          SLACK_FOOTER: "Ci-CD BOT"
